### ISSUE TITLE
Consider moving maintainance to the istio ecosystem

### ISSUE THREAD

**Issue by wleese** [kvij/scuttle#14]
It would be great is this tool would be closer to the Istio project. Here I suggest such a thing. Looking at their response, they have some requirements. Perhaps the owner of this work would be interested?

Please see https://github.com/istio/istio/issues/46991

**Comment by kvij** [comment]
Thank you for the effort you have already put in! I work for a fairly large organization and they have now started to  use my fork company wide. They (as do I) see a single maintainer as a vulnerability, so I'm getting some more maintainers. The previous vulnerability was that the repo was owned by a company and the maintainer lost access (and interest).

I don't know if it is still worth moving with Istio Ambient around the corner. Of course it will take some time before everyone is migrated but the good news is that this solution will be obsolete. If people from the Istio project want to move it close and/or maintain scuttle I'm definitely open to that.

**Comment by kvij** [comment]
The sentiment of in https://github.com/istio/istio/issues/46991 seems that it is not going to be absorbed by them. They also conclude this is a temporary issue.
