### ISSUE TITLE
Major version bump from the redboxllc versioning

### ISSUE THREAD

**Issue by gtmanfred** [kvij/scuttle#5]
Hello, would you possibly reconsider using v1.0.0 and 1.0.1 for your versions and do a bump to 2.0.0 and 2.0.1 so that there is not an overlap between your fork and the original of the redbox repository?

Thanks,
Daniel

**Comment by kvij** [comment]
Hi @gtmanfred, first of all sorry for my late response. I need to set up my messages better.
It is certainly possible to add a 2.0.0 version. I'm curious to find out why this is a problem.
As it is not a library I had not envisioned any issue and that is why I started from v1.0.0.

I'm not going to remove v1.0.0 and v1.0.1 tags but I am willing to Go to v2.0.0 on the next new feature release.

**Comment by kvij** [comment]
That was on purpose. Just like the original code from scuttle was from `envoy-preflight` and versioning was started anew. However I opted to keep the name the same as it is less confusing. This is not just a fork that is intended to merge into ever be merged into redboxllc but a different direction with releases of it's own. People have to update the the docker base image or download/build URLs to switch to this `scuttle`.

What is the reason for forking it internally. Is there something I can do so you don't have to maintain anything?

**Comment by gtmanfred** [comment]
That is a fair argument, because of the new repo, it is similar enough to changing the name and allowing restarting the version numbers.
